-- Add columns for auto-analysis pipeline
-- quick_prompt: lightweight template prompt generated instantly by webhook
-- deep_analysis: full codebase analysis generated by Claude Code via GitHub Actions
-- auto_analyze: whether to trigger deep analysis (mirrors Notion "Auto Analyze" checkbox)
ALTER TABLE notion_planets ADD COLUMN IF NOT EXISTS quick_prompt TEXT;
ALTER TABLE notion_planets ADD COLUMN IF NOT EXISTS deep_analysis TEXT;
ALTER TABLE notion_planets ADD COLUMN IF NOT EXISTS auto_analyze BOOLEAN DEFAULT false;
